### ISSUE TITLE
Wrong Wet Cheeses Display + Name (Filed Guide Issues)

### ISSUE THREAD

**Issue by Joe-org** [eerussianguy/firmalife#88]
Under "Cheese", the page on wet cheese don't display the correct cheeses. Both Showing Dry Cheeses instead of Wet Cheese. The Top display is showing Chevre instead of Feta Cheese, while the Bottom display is showing Cheddar instead of Gouda. 
![2022-09-24_12 48 11](https://user-images.githubusercontent.com/113080914/192081212-17038d86-26e5-4f5b-af0e-106d05ef07be.png)
![2022-09-24_12 48 13](https://user-images.githubusercontent.com/113080914/192081216-5cfe5ac1-81e2-4d68-9fd7-6bce3caeb30f.png)

**Comment by Random-Cookie** [comment]
The recipes for wet cheeses are not shown as you cannot show a barrel recipe in the guide as far as I am aware.

The recipes on the left page are continued from the previous page on dry cheeses, however, the cheddar recipe is repeated instead of showing the Rajya Metok recipe.
![2023-05-07_16 31 01](https://user-images.githubusercontent.com/11795182/236687212-4f2fbe77-b2fe-4781-9c3b-0ae9fc86178d.png)
![2023-05-07_16 30 57](https://user-images.githubusercontent.com/11795182/236687215-4abd8502-1159-4528-83ce-76ae6bc44ed6.png)

Created a fix here, if needed:
https://github.com/eerussianguy/firmalife/pull/128
